
// Objective-C API for talking to the following Go packages
//
//	open_im_sdk/open_im_sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __OpenIMCore_FRAMEWORK_H__
#define __OpenIMCore_FRAMEWORK_H__

#include "Open_im_sdk.objc.h"
#include "Universe.objc.h"

#endif
